# Generated by Django 5.2.5 on 2025-09-24 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'db_table': 'sensor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor obtido')),
                ('tipo', models.CharField(choices=[('SALI', 'Salinidade'), ('OUTR', 'Outro')], default='OUTR', max_length=4, verbose_name='Tipo da leitura')),
                ('data_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data e hora da leitura')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='salinidade.sensor', verbose_name='Sensor (ID)')),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
                'db_table': 'leitura',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['sensor', 'data_hora'], name='leitura_sensor__059e83_idx')],
            },
        ),
    ]
